from typing import Literal

SwingType = Literal["full", "partial", "pitch", "chip"]
Club = Literal["driver", "wood", "hybrid", "iron", "short_iron", "wedge"]

CLUBS: list[Club] = ["driver", "wood", "hybrid", "iron", "short_iron", "wedge"]
SWING_TYPES: list[SwingType] = ["full", "partial", "pitch", "chip"]

# Phases active per swing type. Phase detection is skipped for inactive phases.
ACTIVE_PHASES: dict[SwingType, list[str]] = {
    "full": ["setup", "address", "takeaway", "backswing", "top", "downswing", "impact", "follow_through", "finish"],
    "partial": ["setup", "address", "takeaway", "backswing", "top", "downswing", "impact", "follow_through", "finish"],
    "pitch": ["setup", "address", "backswing", "impact", "follow_through", "finish"],
    "chip": ["setup", "address", "impact", "finish"],
}

Range = tuple[float, float] | None

# IDEAL_RANGES[swing_type][club][metric][phase] -> (min, max) | None
# None means the metric is not evaluated for that phase.
# Angles in degrees; head_drift_* and hip_sway are fractions of body height.
IDEAL_RANGES: dict[SwingType, dict[Club, dict[str, dict[str, Range]]]] = {

    # FULL SWING
    "full": {
        "driver": {
            "spine_angle": {
                "address": (30.0, 38.0),
                "takeaway": (30.0, 38.0),
                "backswing": (28.0, 40.0),
                "top": (28.0, 40.0),
                "downswing": (28.0, 40.0),
                "impact": (25.0, 38.0),
                "follow_through": None,
                "finish": None,
            },
            "knee_flex": {
                "address": (18.0, 28.0),
                "takeaway": (18.0, 28.0),
                "backswing": (16.0, 30.0),
                "top": (16.0, 30.0),
                "downswing": (16.0, 33.0),
                "impact": (13.0, 33.0),
                "follow_through": None,
                "finish": None,
            },
            "hip_rotation": {
                "address": None,
                "takeaway": (5.0, 20.0),
                "backswing": (18.0, 38.0),
                "top": (38.0, 58.0),
                "downswing": (35.0, 58.0),
                "impact": (40.0, 65.0),
                "follow_through": (60.0, 88.0),
                "finish": None,
            },
            "shoulder_rotation": {
                "address": None,
                "takeaway": (8.0, 25.0),
                "backswing": (38.0, 62.0),
                "top": (68.0, 90.0),
                "downswing": (42.0, 72.0),
                "impact": (0.0, 15.0),
                "follow_through": (38.0, 68.0),
                "finish": None,
            },
            "hip_shoulder_separation": {
                "address": None,
                "takeaway": None,
                "backswing": (18.0, 40.0),
                "top": (28.0, 52.0),
                "downswing": (12.0, 42.0),
                "impact": None,
                "follow_through": None,
                "finish": None,
            },
            "head_drift_lateral": {
                "address": None,
                "takeaway": (0.0, 0.04),
                "backswing": (0.0, 0.06),
                "top": (0.0, 0.06),
                "downswing": (0.0, 0.06),
                "impact": (0.0, 0.03),
                "follow_through": None,
                "finish": None,
            },
            "head_drift_vertical": {
                "address": None,
                "takeaway": (0.0, 0.04),
                "backswing": (0.0, 0.05),
                "top": (0.0, 0.05),
                "downswing": (0.0, 0.05),
                "impact": (0.0, 0.04),
                "follow_through": None,
                "finish": None,
            },
            "hip_sway": {
                "address": None,
                "takeaway": (0.0, 0.05),
                "backswing": (0.0, 0.07),
                "top": (0.0, 0.07),
                "downswing": (0.0, 0.09),
                "impact": (0.0, 0.09),
                "follow_through": None,
                "finish": None,
            },
        },

        "wood": {
            "spine_angle": {
                "address": (32.0, 40.0),
                "takeaway": (32.0, 40.0),
                "backswing": (30.0, 42.0),
                "top": (30.0, 42.0),
                "downswing": (30.0, 42.0),
                "impact": (27.0, 40.0),
                "follow_through": None,
                "finish": None,
            },
            "knee_flex": {
                "address": (18.0, 28.0),
                "takeaway": (18.0, 28.0),
                "backswing": (16.0, 30.0),
                "top": (16.0, 30.0),
                "downswing": (16.0, 33.0),
                "impact": (13.0, 33.0),
                "follow_through": None,
                "finish": None,
            },
            "hip_rotation": {
                "address": None,
                "takeaway": (5.0, 20.0),
                "backswing": (18.0, 38.0),
                "top": (36.0, 56.0),
                "downswing": (33.0, 56.0),
                "impact": (38.0, 62.0),
                "follow_through": (58.0, 86.0),
                "finish": None,
            },
            "shoulder_rotation": {
                "address": None,
                "takeaway": (8.0, 24.0),
                "backswing": (36.0, 60.0),
                "top": (65.0, 88.0),
                "downswing": (40.0, 70.0),
                "impact": (0.0, 15.0),
                "follow_through": (36.0, 66.0),
                "finish": None,
            },
            "hip_shoulder_separation": {
                "address": None,
                "takeaway": None,
                "backswing": (17.0, 38.0),
                "top": (26.0, 50.0),
                "downswing": (10.0, 40.0),
                "impact": None,
                "follow_through": None,
                "finish": None,
            },
            "head_drift_lateral": {
                "address": None,
                "takeaway": (0.0, 0.03),
                "backswing": (0.0, 0.05),
                "top": (0.0, 0.05),
                "downswing": (0.0, 0.05),
                "impact": (0.0, 0.025),
                "follow_through": None,
                "finish": None,
            },
            "head_drift_vertical": {
                "address": None,
                "takeaway": (0.0, 0.035),
                "backswing": (0.0, 0.045),
                "top": (0.0, 0.045),
                "downswing": (0.0, 0.045),
                "impact": (0.0, 0.035),
                "follow_through": None,
                "finish": None,
            },
            "hip_sway": {
                "address": None,
                "takeaway": (0.0, 0.045),
                "backswing": (0.0, 0.065),
                "top": (0.0, 0.065),
                "downswing": (0.0, 0.065),
                "impact": (0.0, 0.045),
                "follow_through": None,
                "finish": None,
            },
        },

        "hybrid": {
            "spine_angle": {
                "address": (33.0, 42.0),
                "takeaway": (33.0, 42.0),
                "backswing": (31.0, 44.0),
                "top": (31.0, 44.0),
                "downswing": (31.0, 44.0),
                "impact": (28.0, 42.0),
                "follow_through": None,
                "finish": None,
            },
            "knee_flex": {
                "address": (19.0, 29.0),
                "takeaway": (19.0, 29.0),
                "backswing": (17.0, 31.0),
                "top": (17.0, 31.0),
                "downswing": (17.0, 34.0),
                "impact": (14.0, 34.0),
                "follow_through": None,
                "finish": None,
            },
            "hip_rotation": {
                "address": None,
                "takeaway": (5.0, 20.0),
                "backswing": (17.0, 36.0),
                "top": (34.0, 54.0),
                "downswing": (32.0, 54.0),
                "impact": (36.0, 60.0),
                "follow_through": (56.0, 84.0),
                "finish": None,
            },
            "shoulder_rotation": {
                "address": None,
                "takeaway": (7.0, 23.0),
                "backswing": (35.0, 58.0),
                "top": (63.0, 86.0),
                "downswing": (38.0, 68.0),
                "impact": (0.0, 15.0),
                "follow_through": (34.0, 64.0),
                "finish": None,
            },
            "hip_shoulder_separation": {
                "address": None,
                "takeaway": None,
                "backswing": (16.0, 36.0),
                "top": (25.0, 48.0),
                "downswing": (9.0, 38.0),
                "impact": None,
                "follow_through": None,
                "finish": None,
            },
            "head_drift_lateral": {
                "address": None,
                "takeaway": (0.0, 0.03),
                "backswing": (0.0, 0.05),
                "top": (0.0, 0.05),
                "downswing": (0.0, 0.05),
                "impact": (0.0, 0.022),
                "follow_through": None,
                "finish": None,
            },
            "head_drift_vertical": {
                "address": None,
                "takeaway": (0.0, 0.032),
                "backswing": (0.0, 0.042),
                "top": (0.0, 0.042),
                "downswing": (0.0, 0.042),
                "impact": (0.0, 0.032),
                "follow_through": None,
                "finish": None,
            },
            "hip_sway": {
                "address": None,
                "takeaway": (0.0, 0.042),
                "backswing": (0.0, 0.062),
                "top": (0.0, 0.062),
                "downswing": (0.0, 0.062),
                "impact": (0.0, 0.042),
                "follow_through": None,
                "finish": None,
            },
        },

        "iron": {
            "spine_angle": {
                "address": (35.0, 45.0),
                "takeaway": (35.0, 45.0),
                "backswing": (33.0, 47.0),
                "top": (33.0, 47.0),
                "downswing": (33.0, 47.0),
                "impact": (30.0, 45.0),
                "follow_through": None,
                "finish": None,
            },
            "knee_flex": {
                "address": (20.0, 30.0),
                "takeaway": (20.0, 30.0),
                "backswing": (18.0, 32.0),
                "top": (18.0, 32.0),
                "downswing": (18.0, 35.0),
                "impact": (15.0, 35.0),
                "follow_through": None,
                "finish": None,
            },
            "hip_rotation": {
                "address": None,
                "takeaway": (5.0, 20.0),
                "backswing": (16.0, 35.0),
                "top": (32.0, 52.0),
                "downswing": (30.0, 52.0),
                "impact": (34.0, 58.0),
                "follow_through": (54.0, 82.0),
                "finish": None,
            },
            "shoulder_rotation": {
                "address": None,
                "takeaway": (7.0, 23.0),
                "backswing": (33.0, 56.0),
                "top": (60.0, 84.0),
                "downswing": (36.0, 66.0),
                "impact": (0.0, 15.0),
                "follow_through": (32.0, 62.0),
                "finish": None,
            },
            "hip_shoulder_separation": {
                "address": None,
                "takeaway": None,
                "backswing": (15.0, 35.0),
                "top": (24.0, 46.0),
                "downswing": (8.0, 36.0),
                "impact": None,
                "follow_through": None,
                "finish": None,
            },
            "head_drift_lateral": {
                "address": None,
                "takeaway": (0.0, 0.03),
                "backswing": (0.0, 0.05),
                "top": (0.0, 0.05),
                "downswing": (0.0, 0.05),
                "impact": (0.0, 0.02),
                "follow_through": None,
                "finish": None,
            },
            "head_drift_vertical": {
                "address": None,
                "takeaway": (0.0, 0.03),
                "backswing": (0.0, 0.04),
                "top": (0.0, 0.04),
                "downswing": (0.0, 0.04),
                "impact": (0.0, 0.03),
                "follow_through": None,
                "finish": None,
            },
            "hip_sway": {
                "address": None,
                "takeaway": (0.0, 0.04),
                "backswing": (0.0, 0.06),
                "top": (0.0, 0.06),
                "downswing": (0.0, 0.06),
                "impact": (0.0, 0.04),
                "follow_through": None,
                "finish": None,
            },
        },

        "short_iron": {
            "spine_angle": {
                "address": (38.0, 48.0),
                "takeaway": (38.0, 48.0),
                "backswing": (36.0, 50.0),
                "top": (36.0, 50.0),
                "downswing": (36.0, 50.0),
                "impact": (33.0, 48.0),
                "follow_through": None,
                "finish": None,
            },
            "knee_flex": {
                "address": (20.0, 30.0),
                "takeaway": (20.0, 30.0),
                "backswing": (18.0, 32.0),
                "top": (18.0, 32.0),
                "downswing": (18.0, 35.0),
                "impact": (15.0, 35.0),
                "follow_through": None,
                "finish": None,
            },
            "hip_rotation": {
                "address": None,
                "takeaway": (4.0, 18.0),
                "backswing": (14.0, 32.0),
                "top": (28.0, 48.0),
                "downswing": (26.0, 48.0),
                "impact": (30.0, 54.0),
                "follow_through": (50.0, 78.0),
                "finish": None,
            },
            "shoulder_rotation": {
                "address": None,
                "takeaway": (6.0, 20.0),
                "backswing": (30.0, 52.0),
                "top": (56.0, 80.0),
                "downswing": (32.0, 62.0),
                "impact": (0.0, 15.0),
                "follow_through": (28.0, 58.0),
                "finish": None,
            },
            "hip_shoulder_separation": {
                "address": None,
                "takeaway": None,
                "backswing": (13.0, 32.0),
                "top": (22.0, 44.0),
                "downswing": (7.0, 34.0),
                "impact": None,
                "follow_through": None,
                "finish": None,
            },
            "head_drift_lateral": {
                "address": None,
                "takeaway": (0.0, 0.025),
                "backswing": (0.0, 0.04),
                "top": (0.0, 0.04),
                "downswing": (0.0, 0.04),
                "impact": (0.0, 0.018),
                "follow_through": None,
                "finish": None,
            },
            "head_drift_vertical": {
                "address": None,
                "takeaway": (0.0, 0.028),
                "backswing": (0.0, 0.038),
                "top": (0.0, 0.038),
                "downswing": (0.0, 0.038),
                "impact": (0.0, 0.028),
                "follow_through": None,
                "finish": None,
            },
            "hip_sway": {
                "address": None,
                "takeaway": (0.0, 0.035),
                "backswing": (0.0, 0.055),
                "top": (0.0, 0.055),
                "downswing": (0.0, 0.055),
                "impact": (0.0, 0.035),
                "follow_through": None,
                "finish": None,
            },
        },

        "wedge": {
            "spine_angle": {
                "address": (40.0, 50.0),
                "takeaway": (40.0, 50.0),
                "backswing": (38.0, 52.0),
                "top": (38.0, 52.0),
                "downswing": (38.0, 52.0),
                "impact": (35.0, 50.0),
                "follow_through": None,
                "finish": None,
            },
            "knee_flex": {
                "address": (20.0, 30.0),
                "takeaway": (20.0, 30.0),
                "backswing": (18.0, 32.0),
                "top": (18.0, 32.0),
                "downswing": (18.0, 35.0),
                "impact": (15.0, 35.0),
                "follow_through": None,
                "finish": None,
            },
            "hip_rotation": {
                "address": None,
                "takeaway": (3.0, 16.0),
                "backswing": (12.0, 28.0),
                "top": (24.0, 44.0),
                "downswing": (22.0, 42.0),
                "impact": (25.0, 48.0),
                "follow_through": (44.0, 70.0),
                "finish": None,
            },
            "shoulder_rotation": {
                "address": None,
                "takeaway": (5.0, 18.0),
                "backswing": (26.0, 48.0),
                "top": (50.0, 74.0),
                "downswing": (28.0, 58.0),
                "impact": (0.0, 15.0),
                "follow_through": (24.0, 54.0),
                "finish": None,
            },
            "hip_shoulder_separation": {
                "address": None,
                "takeaway": None,
                "backswing": (11.0, 28.0),
                "top": (18.0, 38.0),
                "downswing": (5.0, 30.0),
                "impact": None,
                "follow_through": None,
                "finish": None,
            },
            "head_drift_lateral": {
                "address": None,
                "takeaway": (0.0, 0.022),
                "backswing": (0.0, 0.035),
                "top": (0.0, 0.035),
                "downswing": (0.0, 0.035),
                "impact": (0.0, 0.015),
                "follow_through": None,
                "finish": None,
            },
            "head_drift_vertical": {
                "address": None,
                "takeaway": (0.0, 0.025),
                "backswing": (0.0, 0.035),
                "top": (0.0, 0.035),
                "downswing": (0.0, 0.035),
                "impact": (0.0, 0.025),
                "follow_through": None,
                "finish": None,
            },
            "hip_sway": {
                "address": None,
                "takeaway": (0.0, 0.03),
                "backswing": (0.0, 0.05),
                "top": (0.0, 0.05),
                "downswing": (0.0, 0.05),
                "impact": (0.0, 0.03),
                "follow_through": None,
                "finish": None,
            },
        },
    },

    # PARTIAL SWING (half / 3-quarter)
    "partial": {
        club: {
            "spine_angle": {
                "address": (35.0, 48.0),
                "takeaway": (35.0, 48.0),
                "backswing": (33.0, 50.0),
                "top": (33.0, 50.0),
                "downswing": (33.0, 50.0),
                "impact": (30.0, 48.0),
                "follow_through": None,
                "finish": None,
            },
            "knee_flex": {
                "address": (20.0, 30.0),
                "takeaway": (20.0, 30.0),
                "backswing": (18.0, 32.0),
                "top": (18.0, 32.0),
                "downswing": (18.0, 35.0),
                "impact": (15.0, 35.0),
                "follow_through": None,
                "finish": None,
            },
            "hip_rotation": {
                "address": None,
                "takeaway": (3.0, 15.0),
                "backswing": (10.0, 26.0),
                "top": (18.0, 34.0),
                "downswing": (16.0, 32.0),
                "impact": (20.0, 38.0),
                "follow_through": (35.0, 58.0),
                "finish": None,
            },
            "shoulder_rotation": {
                "address": None,
                "takeaway": (5.0, 20.0),
                "backswing": (22.0, 46.0),
                "top": (38.0, 62.0),
                "downswing": (18.0, 48.0),
                "impact": (0.0, 12.0),
                "follow_through": (28.0, 58.0),
                "finish": None,
            },
            "hip_shoulder_separation": {
                "address": None,
                "takeaway": None,
                "backswing": (10.0, 26.0),
                "top": (16.0, 32.0),
                "downswing": (6.0, 28.0),
                "impact": None,
                "follow_through": None,
                "finish": None,
            },
            "head_drift_lateral": {
                "address": None,
                "takeaway": (0.0, 0.02),
                "backswing": (0.0, 0.03),
                "top": (0.0, 0.03),
                "downswing": (0.0, 0.03),
                "impact": (0.0, 0.015),
                "follow_through": None,
                "finish": None,
            },
            "head_drift_vertical": {
                "address": None,
                "takeaway": (0.0, 0.022),
                "backswing": (0.0, 0.032),
                "top": (0.0, 0.032),
                "downswing": (0.0, 0.032),
                "impact": (0.0, 0.022),
                "follow_through": None,
                "finish": None,
            },
            "hip_sway": {
                "address": None,
                "takeaway": (0.0, 0.025),
                "backswing": (0.0, 0.04),
                "top": (0.0, 0.04),
                "downswing": (0.0, 0.04),
                "impact": (0.0, 0.025),
                "follow_through": None,
                "finish": None,
            },
        }
        for club in CLUBS
    },

    # PITCH
    "pitch": {
        club: {
            "spine_angle": {
                "address": (38.0, 50.0),
                "backswing": (36.0, 52.0),
                "impact": (34.0, 50.0),
                "follow_through": None,
                "finish": None,
            },
            "knee_flex": {
                "address": (20.0, 30.0),
                "backswing": (18.0, 32.0),
                "impact": (15.0, 35.0),
                "follow_through": None,
                "finish": None,
            },
            "hip_rotation": {
                "address": None,
                "backswing": (5.0, 22.0),
                "impact": (12.0, 28.0),
                "follow_through": (25.0, 50.0),
                "finish": None,
            },
            "shoulder_rotation": {
                "address": None,
                "backswing": (18.0, 42.0),
                "impact": (0.0, 12.0),
                "follow_through": (22.0, 50.0),
                "finish": None,
            },
            "hip_shoulder_separation": {
                "address": None,
                "backswing": (8.0, 24.0),
                "impact": None,
                "follow_through": None,
                "finish": None,
            },
            "head_drift_lateral": {
                "address": None,
                "backswing": (0.0, 0.02),
                "impact": (0.0, 0.012),
                "follow_through": None,
                "finish": None,
            },
            "head_drift_vertical": {
                "address": None,
                "backswing": (0.0, 0.022),
                "impact": (0.0, 0.018),
                "follow_through": None,
                "finish": None,
            },
            "hip_sway": {
                "address": None,
                "backswing": (0.0, 0.02),
                "impact": (0.0, 0.015),
                "follow_through": None,
                "finish": None,
            },
        }
        for club in CLUBS
    },

    # CHIP
    "chip": {
        club: {
            "spine_angle": {
                "address": (40.0, 52.0),
                "impact": (38.0, 52.0),
                "finish": None,
            },
            "knee_flex": {
                "address": (20.0, 30.0),
                "impact": (18.0, 32.0),
                "finish": None,
            },
            "hip_rotation": {
                "address": None,
                "impact": (5.0, 18.0),
                "finish": None,
            },
            "shoulder_rotation": {
                "address": None,
                "impact": (0.0, 12.0),
                "finish": None,
            },
            "hip_shoulder_separation": {
                "address": None,
                "impact": None,
                "finish": None,
            },
            "head_drift_lateral": {
                "address": None,
                "impact": (0.0, 0.01),
                "finish": None,
            },
            "head_drift_vertical": {
                "address": None,
                "impact": (0.0, 0.012),
                "finish": None,
            },
            "hip_sway": {
                "address": None,
                "impact": (0.0, 0.01),
                "finish": None,
            },
        }
        for club in CLUBS
    },
}

# MediaPipe settings
POSE_MODEL_COMPLEXITY = 1 # 0=lite, 1=full, 2=heavy
POSE_MIN_DETECTION_CONFIDENCE = 0.5
POSE_MIN_TRACKING_CONFIDENCE = 0.5

# MediaPipe Pose landmark indices used across the pipeline
LM_HEAD = 0
LM_L_SHOULDER = 11
LM_R_SHOULDER = 12
LM_L_ELBOW = 13
LM_L_WRIST = 15
LM_L_HIP = 23
LM_R_HIP = 24

# Savitzky-Golay landmark smoothing
SMOOTHING_WINDOW = 7 # must be odd
SMOOTHING_POLYORDER = 2
